### ISSUE TITLE
Add non-existing ros user and group

### ISSUE THREAD

**Issue by ramsafin** [chupakabra1996/ansible-ros-kinetic-playbook#1]
In case if vagrant is not being used remote user may not exist. That's why it needs to be created.
Something like the following should be done in ros role:
```yaml
tasks:
...
- name: check if ros user and group exist
...
- name: add ros user and group (with sudo privileges) 
...
```
